### ISSUE TITLE
Post-processing stylization doesn't apply 

### ISSUE THREAD

**Issue by niskander** [dustyroom-studio/quibli-doc#13]
Hello, thanks for the lovely shaders and scenes. The nature scene works perfectly with the post-processing stylization, but for some reason the city scene doesn't. The renderer is set correctly and uses the Quibli city scene renderer (I also tried the nature one, which didn't fix it). There are no errors or warnings in the console.

**To Reproduce**
Import package and open city demo scene

**Screenshots**
<img width="1337" alt="Screen Shot 2022-06-22 at 9 31 40 AM" src="https://user-images.githubusercontent.com/1988272/175087935-3814141a-074d-4423-afff-66430b68a3e1.png">

**Unity details**:
Quibli version 1.4.8
Unity 2021.3.4f1
Dev platform: OSXEditor
Target platform: StandaloneOSX
URP installed: True, version 12.1.7
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: UniversalRP-HighQuality
Graphics config: UniversalRP-HighQuality

**Comment by niskander** [comment]
For comparison here is the nature scene which doesn't have this issue
<img width="1006" alt="Screen Shot 2022-06-22 at 9 33 57 AM" src="https://user-images.githubusercontent.com/1988272/175088652-24a38723-dbd3-4e5d-9e7b-866bdc7cdc7d.png">

**Comment by dustyroom-studio** [comment]
Thank you for reporting this, we're able to reproduce the issue and will fix it ASAP.

**Comment by dustyroom-studio** [comment]
We've released an update on the Asset Store that addresses this issue. Please re-download and re-import Quibli.

**Comment by niskander** [comment]
Confirming that it's fixed, thanks for the quick fix!
