### ISSUE TITLE
Emission maps

### ISSUE THREAD

**Issue by Plnda** [dustyroom-studio/quibli-doc#19]
It would be awesome to include Emission maps in the stylized shader

**Comment by dustyroom-studio** [comment]
Thanks for the suggestion. We've heard this feedback, so probably will add it, but I can't give a definite timeline at this point.

**Comment by Plnda** [comment]
@dustyroom-studio It seems like the shader already had a near working implemenation of supporting emissions. I fixed the code myself for now.

**Comment by dustyroom-studio** [comment]
Hi, we've just implemented the Emission maps support. The update should go live soon.
