### ISSUE TITLE
Base Import Causing multiple Errors and Asset pack does not work

### ISSUE THREAD

**Issue by lustfulbunzy** [dustyroom-studio/quibli-doc#2]
**Describe the bug**
Multiple Errors upon Import

**To Reproduce**
1. Literally Imported it

**Expected behavior**
Can't use it

**Screenshots**

**Unity details:**
 - Quibli version: 1.0.1
 - Unity version: 2020.3.18f1
 - Graphics Pipeline: [Bult-in or URP]
 - URP version (if applicable): [e.g. 10.3.1]
 - Development OS: Windows

**Build platform:**
 - Platform: Pc
 - Test device: Pc
**Additional context**
There is to many errors and problems for me to take screenshots and show you. It very well may be my fault and I might not have all the required assets, but it is no where stated that any were needed.

**Comment by dustyroom-studio** [comment]
Hi,

Could you please do the following:
- Check whether you installed Quibli from the Package Manager as described in the video [here](https://quibli.dustyroom.com/installation/)
- Go through the list of known possible reasons of the importing errors [here](https://quibli.dustyroom.com/installation/#troubleshooting)
- Specify whether you use URP or Built-In RP project. Quibli is working in URP only.
- Go to the Console panel, make a screenshot of the errors (at least, of some of them), and add them here.

You don't need to have any additional assets to make Quibli work - you need only a **URP** project, which is started in Unity **at least 2020.3.1f1**

Any additional info, screenshots, screen recordings about the errors or the set-up process will help us find the cause of the issue and will reduce the guess work.
