### ISSUE TITLE
The option to disable clouds.

### ISSUE THREAD

**Issue by etonix** [dustyroom-studio/quibli-doc#20]
I'd like to use COZY: Weather 2 in my project, but the Quibli clouds keep overtaking the skybox.

Is there a way to disable the Quibli clouds?

[Debug]
Quibli version 1.5.0
Unity 2021.3.10f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.7
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: Quibli URP Config
Graphics config: Quibli URP Config
![image](https://user-images.githubusercontent.com/13529724/197877169-c43e5ed3-d62b-4881-bd68-720b111b1c72.png)

**Comment by dustyroom-studio** [comment]
Hi,

Thank you for your details and for the screenshot.

I'm not sure I understood your question fully. Do you have an issue with the Quibli Cloud2D shader not allowing to disable the meshes from the scene?

Both [Cloud2D](https://quibli.dustyroom.com/cloud2d-shader/) and [Cloud3D](https://quibli.dustyroom.com/cloud3d-shader/) shaders are applied on the meshes, they don't distribute the models.

If you were asking about how to disable the auto movement of the clouds, please go to the Cloud2D material and set the **Offset Speed** parameter to X : 0, Y : 0, which makes the clouds static.

Please, let me know if you meant something else.

**Comment by etonix** [comment]
I'd like to not have the Quibli clouds included in the scene at all, but cannot find where to disable them. Is there an option?

**Comment by dustyroom-studio** [comment]
Sure.
In the Hierarchy panel, expand the Scenery folder, locate the clouds folder and turn it off or delete the folder. Depending on a demo scene, here's how the folders with clouds look:

**City**:
![quibli-demo-city-hierarchy-clouds](https://user-images.githubusercontent.com/74666746/197899454-5d6e5b23-d5e2-498e-a83b-3a29e0727267.png)

**Nature**:
![quibli-demo-nature-hierarchy-clouds](https://user-images.githubusercontent.com/74666746/197899508-50d25e06-2674-403b-85f0-9c2f961e99d4.png)

**Sample Scene with Quibli**:
![quibli-demo-sample-scene-hierarchy-clouds](https://user-images.githubusercontent.com/74666746/197899535-314fa40d-389d-402e-a09a-7de56815e4ca.png)
