### ISSUE TITLE
Curved World support

### ISSUE THREAD

**Issue by KevinRoussel** [dustyroom-studio/quibli-doc#21]
**Is your feature request related to a problem? Please describe.**
Hello world

I am trying to merge the CurvedWorld shader with Quibli. On FlatKit I managed to put CurvedWorld in place by changing some code but on Quibli I don't have a satisfactory result, at best the mesh curves well but the visual rendering is bad 

**Describe the solution you'd like**
I would like to have like on the flatkit with the majority of the code that is available and that can be uncommented

**Additional context**
https://user-images.githubusercontent.com/9155865/201644672-e042ade8-bb8c-40ff-8f66-fea01a3059bb.mp4

**Comment by dustyroom-studio** [comment]
Hi, thank you for the video.
To be able to understand this issue better and probably replicate it, I'll need to ask you for more details. 
- Please, locate the **Readme** file, by default in Assets/Quibli and copy the debug info from its Inspector panel (there is a **Copy** button), paste the copied info here. Or just make a screenshot of the panel.
- Have you installed Quibli as described in the [guide](https://quibli.dustyroom.com/installation/)?
- Are there any errors about Quibli in the Console?
- Which part of Quibli did you use instead of Flat Kit? Could you share any details on how and what you successfully modified in Flat Kit but not in Quibli?
- What exactly, to your mind, looks bad in your video example?
- Could you please clarify what did you mean when asking about the available and uncommented code?

Thank you

**Comment by KevinRoussel** [comment]
Hello,

Thanks for the quick answer :)

DebugInfo: 
> Quibli version 1.5.0
> Unity 2021.3.12f1
> Dev platform: WindowsEditor
> Target platform: StandaloneWindows64
> URP installed: True, version 12.1.7
> Render pipeline: UniversalPipeline
> Color space: Linear
> Quality config: Quibli URP Config
> Graphics config: Quibli URP Config

Quibli is installed as described in the guide yes with the updated renderer in URP.

There is no error in the console, the shader code compiles, but the rendering doesn't seem to be correct, I prepare an empty project with only Quibli and CurvedWorld to isolate the problem.

I am not very experienced with the shader code, but for me there must be a problem with the normal that generates the shadow, I would like that there is no shadow nor height gradient is not influenced by the curvature of the world.

In the Flatkit there is some code to support curvedWorld (screen), using this code and moving some lines it does the job exactly as I expect, I have fixed a problem with Flatkit & CurvedWorld, if you want I can provide you my version of the code. 
Ideally I would like to have the equivalent of the flatkit code for quibli, the integration is very well done in the flatkit and it was very easy to add.
![image](https://user-images.githubusercontent.com/9155865/201702372-34f6c06f-168c-4284-98fd-bce6411f1fae.png)
![image](https://user-images.githubusercontent.com/9155865/201702535-8830f81a-1b3a-4d48-93b1-e266a6837361.png)

**Comment by KevinRoussel** [comment]
That's what I did
I took the Flatkit code and applied the same logic. The piece of code from LitForwardPass_DR.hlsl (flatkit) I put in the QuibliVertex.hlsl

I have an empty project with FlatKit, Quibli and CurvedWorld and I reproduce my shadow problem. I can provide you the project (Unity 2021.3.12f1 and all up to date)

**Comment by KevinRoussel** [comment]
Yes I have this, I can have made a mistake for the moment I have this code (screen)
![image](https://user-images.githubusercontent.com/9155865/201718981-98d8815d-2316-48c5-b817-4a15c644610c.png)

Update, in Flatkit when activating Unity's shadow I have the same behaviour. (screen, up Quibli, down Flatkit)
How can I avoid having "curved shadows"? I would like to have the shading not curved because it generates visual glitches
![image](https://user-images.githubusercontent.com/9155865/201719110-a1061177-7b9e-439d-99db-64898c36ee06.png)

**Comment by dustyroom-studio** [comment]
Great, now I think you also need to copy `ShadowPassVertex` and `ShadowPassFragment` and customize them to support Curved World. We do not customize them in Quibli to support more Unity versions, that's why we can't have full Curved World integration out of the box.

**Comment by KevinRoussel** [comment]
Aaaaah yes I understand it works thank you!
I would not have succeeded without your help.

https://user-images.githubusercontent.com/9155865/201727807-0ca263fe-ea89-4d46-9301-50fb436b5fc0.mp4
