### ISSUE TITLE
No export mesh button in foliage generator

### ISSUE THREAD

**Issue by skoolknot** [dustyroom-studio/quibli-doc#23]
**Describe the bug**
There is no export mesh button in foliage generator

**To Reproduce**
1. Drag foliage generator prefab into scene
2. There is no export mesh button in inspector

**Expected behavior**
No export mesh button in foliage generator

**Screenshots**
![image](https://user-images.githubusercontent.com/875694/205667343-2c4fea75-54ee-4acf-8b7f-4ee66dbab1fe.png)

**Unity details**:
Quibli version 1.7.0
Unity 2021.3.15f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 12.1.8
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: UniversalRenderPipelineAsset_High
Graphics config: UniversalRenderPipelineAsset_High

**Additional context**
-

**Comment by dustyroom-studio** [comment]
Thanks for reporting this. A few questions to help us debug:

1. Are there any errors in the console?
2. Did you include the folder `Quibli/Utils/EditorAttributes` when importing the asset?

**Comment by skoolknot** [comment]
1. No.
2. Yes.
![image](https://user-images.githubusercontent.com/875694/205781600-8e0308e7-4f12-4e40-8c08-a858c85d4bb4.png)

We believe it is probably conflicted with NaughtyAttributes as we have already installed it beforehand. It is possible in our case?

Current workaround is to set 'Export On Edit' to true.

**Comment by dustyroom-studio** [comment]
I'm uploading a fix to the Asset Store, it should appear in a few minutes, please update Quibli.
