### ISSUE TITLE
StylizedLit error in unity 2022.3.15f1

### ISSUE THREAD

**Issue by c-pun-ninja** [dustyroom-studio/quibli-doc#27]
**Describe the bug**
After I upgraded my project from 2021 -> 2022.3.15f1, I found my old Quibli version is buggy, so we downloaded the latest 2.1.0 package. I replaced it by clicking clear cache and then delete the Quibli folder, and import the new package.
My scene turned pink and it shown shader error as screenshot attached.

**To Reproduce**
1. Install unity editor 2022.3.15f1
2. Import Quibli 2.1.0 and set renderpipeline with sample URP  
3. Change additional light to "per pixel"
4. See error by assign stylized lit shader to 3d objects.
5. See error in Console tab or inspector of Quibli/Shaders/StylizedLit.shader  

**Expected behavior**
No shader error, material will not turn pink and also not whitish. 

**Screenshots**
![additional_light_per_vertex](https://github.com/dustyroom-studio/quibli-doc/assets/108648793/036479e3-24b0-42f1-a99a-3d1b68f38aab)
![StylizedLit_error](https://github.com/dustyroom-studio/quibli-doc/assets/108648793/71d69277-f4e5-4dea-bd2b-7e951d579452)

**Unity details**:
(Use the `Copy` button in your project *Quibli/Readme* file and paste here.)
Quibli version 2.1.0
Unity 2022.3.15f1
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 14.0.9
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: N/A
Graphics config: UniversalRP-2HighQuality

**Additional context**
I tried switching between sample URP settings from your package, seems additional light "Per Pixel" and "Per Vertex" show different result. When I set to "Per Pixel" , the whole scene became whitish that result is not same as 2021. 
Switching renderer between deferred or forward have no differences.
I wonder if there is any difference if I downloaded the package using 2021 or lower for unity 2022.3.15f1.  

If there are any easy way to solve, please send instructions to my email, many thanks 
c-pun@nextninja.co.jp

**Comment by dustyroom-studio** [comment]
Thank you for the detailed description! We are able to reproduce the issue and will release a fix in a Quibli update today.
Please re-open the issue if the errors do not get resolved.
