### ISSUE TITLE
Error when adding Stylized Render Feature

### ISSUE THREAD

**Issue by Morphexe** [dustyroom-studio/quibli-doc#8]
**Describe the bug**
Whenever I add the Stylized Detail Renderer feature Unity Throws a error at runtime saying : 

`You can only call cameraColorTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed.`

**To Reproduce**
1. Add the package
2. Click the Readme button to set everything up
3.  Realize that postprocessing is not working
4. Add the missing renderer feature
5. See the error on the console

**Expected behavior**
No Error Show

**Screenshots**
![image](https://user-images.githubusercontent.com/17990387/148056805-bf797acf-41c8-474d-abb0-7859e6a12914.png)
![image](https://user-images.githubusercontent.com/17990387/148056833-fc5ff0b7-2278-465f-9433-56dfbf2db41c.png)

**Unity details**:
Quibli version 1.2.5
Unity 2022.1.0b2
Dev platform: WindowsEditor
Target platform: StandaloneWindows64
URP installed: True, version 13.1.3
Render pipeline: UniversalPipeline
Color space: Linear
Quality config: Quibli URP Config
Graphics config: Quibli URP Config

**Additional context**

**Comment by Morphexe** [comment]
I have updated to version 1.3.0 and the same error persists.

**Comment by dustyroom-studio** [comment]
Hi, thank you for the details.

Could you please try it in a non-beta Unity version?
We are working on the implementation of the Unity 2022 support, but the released version of Quibli requires an officially released version of Unity, which Unity 2022 currently isn't. You can read about this in the troubleshooting section of the Quibli doc [[here](https://quibli.dustyroom.com/installation/#after-importing-quibli-gives-errors)].

**Comment by Morphexe** [comment]
Oh I see, apologies. I read through the docs, but didn`t realize it was unity version specific. Apologies.
On a side note, do you have a  estimation for 2022 release  - just to know if Its worth me looking in updating it myself, or wait :).

 Feel free to close the issue.

**Comment by dustyroom-studio** [comment]
Thank you for your reply.

Many assets are version-specific (developers check the supported versions and pipelines during the submission to the Asset Store). The compatibility info for such assets can be found on the very Asset Store pages, under the 'Render pipeline compatibility' paragraph.

Usually, the adjustments take not too much time, but with the introduction of the version 2022, Unity changed quite a lot in URP, which would take us some time to debug everything in our assets. Although it's our main priority to get this done as soon as possible, we can't give any approximate times. If you are on a tight deadline, I'd suggest you to postpone the upgrade. 2022 beta is quite buggy for now, we found a few quirks ourselves there and are waiting for the fixes.
